import type { Metadata } from "next";
import { Inter, Judson } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const judson = Judson({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-judson",
  weight: "400",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-taviraj",
  weight: "400",
});

export const metadata: Metadata = {
  title: "AllBeer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn(inter.variable, judson.variable)}>{children}</body>
    </html>
  );
}
